import Head from "next/head";
// import { Lines } from "react-preloaders";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import About from "../components/About";
import Skill from "../components/Skill";
import Projects from "../components/Projects";
import Github from "../components/Github";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import HorizontalScroll from "../components/HorizontalScroll";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Syed Bilal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Lines color={"#20c863"} background="#2d2e2e" /> */}
      <HorizontalScroll />
      <Navbar />
      <Hero />
      <About />
      <Skill />
      <Projects />
      <Github />
      <Contact />
      <Footer />
    </div>
  );
}
